CREATE TABLE IF NOT EXISTS `val_custom_props` (
  `plate` VARCHAR(32) NOT NULL,
  `props` LONGTEXT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
